[2022-08-20 10:23:02,566] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [queued]>
[2022-08-20 10:23:04,503] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [queued]>
[2022-08-20 10:23:04,674] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 10:23:04,756] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-20 10:23:04,797] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 10:23:06,553] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_file> on 2022-08-20 03:00:00+00:00
[2022-08-20 10:23:07,072] {standard_task_runner.py:52} INFO - Started process 4674 to run task
[2022-08-20 10:23:07,665] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'waiting_for_file', 'scheduled__2022-08-20T03:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmpbc7s1f6u', '--error-file', '/tmp/tmpvjjztj71']
[2022-08-20 10:23:07,735] {standard_task_runner.py:80} INFO - Job 37: Subtask waiting_for_file
[2022-08-20 10:23:14,336] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-20 10:23:25,373] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=waiting_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-20T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-20T03:00:00+00:00
[2022-08-20 10:23:26,750] {base.py:68} INFO - Using connection ID 'ya_***_workshop_file_path' for task execution.
[2022-08-20 10:23:26,792] {filesystem.py:58} INFO - Poking for file C:/Users/AbduevSA-LA/Desktop/Yandex/Airflow_workshop/workshop_***-main/
[2022-08-20 10:23:28,035] {taskinstance.py:1873} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2022-08-20 10:23:28,801] {local_task_job.py:221} WARNING - State of this instance has been externally set to up_for_reschedule. Terminating instance.
[2022-08-20 10:23:28,941] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 4674. PIDs of all processes in the group: [4674]
[2022-08-20 10:23:29,007] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 4674
[2022-08-20 10:23:29,107] {process_utils.py:75} INFO - Process psutil.Process(pid=4674, status='terminated', exitcode=0, started='10:23:06') (4674) terminated with exit code 0
[2022-08-20 11:34:53,185] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [queued]>
[2022-08-20 11:34:53,434] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [queued]>
[2022-08-20 11:34:53,437] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 11:34:53,439] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-20 11:34:53,440] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 11:34:53,993] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_file> on 2022-08-20 03:00:00+00:00
[2022-08-20 11:34:54,136] {standard_task_runner.py:52} INFO - Started process 4776 to run task
[2022-08-20 11:34:54,487] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'waiting_for_file', 'scheduled__2022-08-20T03:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmpfcwa5sye', '--error-file', '/tmp/tmpcso8g3fa']
[2022-08-20 11:34:54,502] {standard_task_runner.py:80} INFO - Job 45: Subtask waiting_for_file
[2022-08-20 11:34:56,264] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-20 11:34:57,787] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=waiting_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-20T03:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-20T03:00:00+00:00
[2022-08-20 11:34:58,067] {base.py:68} INFO - Using connection ID 'ya_***_workshop_file_path' for task execution.
[2022-08-20 11:34:58,080] {filesystem.py:58} INFO - Poking for file C:/Users/AbduevSA-LA/Desktop/Yandex/Airflow_workshop/workshop_***-main/
[2022-08-20 11:34:58,085] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: yandex-rates-test
[2022-08-20 11:34:58,171] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=yandex-rates-test, task_id=waiting_for_file, execution_date=20220820T030000, start_date=20220820T113453, end_date=20220820T113458
[2022-08-20 11:34:58,296] {standard_task_runner.py:97} ERROR - Failed to execute job 45 for task waiting_for_file (Snap. Time is OUT. DAG id: yandex-rates-test; 4776)
[2022-08-20 11:34:58,757] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-20 11:34:59,470] {logging_mixin.py:115} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7fdb0783b690>, 'dag': <DAG: yandex-rates-test>, 'dag_run': <DagRun yandex-rates-test @ 2022-08-20 03:00:00+00:00: scheduled__2022-08-20T03:00:00+00:00, externally triggered: False>, 'data_interval_end': DateTime(2022, 8, 20, 6, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2022, 8, 20, 3, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2022-08-20', 'ds_nodash': '20220820', 'execution_date': DateTime(2022, 8, 20, 3, 0, 0, tzinfo=Timezone('UTC')), 'inlets': [], 'logical_date': DateTime(2022, 8, 20, 3, 0, 0, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': '2022-08-20', 'next_ds_nodash': '20220820', 'next_execution_date': DateTime(2022, 8, 20, 6, 0, 0, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': '2022-08-20', 'prev_ds_nodash': '20220820', 'prev_execution_date': DateTime(2022, 8, 20, 0, 0, 0, tzinfo=Timezone('UTC')), 'prev_execution_date_success': None, 'prev_start_date_success': None, 'run_id': 'scheduled__2022-08-20T03:00:00+00:00', 'task': <Task(FileSensor): waiting_for_file>, 'task_instance': <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [failed]>, 'task_instance_key_str': 'yandex-rates-test__waiting_for_file__20220820', 'test_mode': False, 'ti': <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-20T03:00:00+00:00 [failed]>, 'tomorrow_ds': '2022-08-21', 'tomorrow_ds_nodash': '20220821', 'ts': '2022-08-20T03:00:00+00:00', 'ts_nodash': '20220820T030000', 'ts_nodash_with_tz': '20220820T030000+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': '2022-08-19', 'yesterday_ds_nodash': '20220819', 'exception': AirflowSensorTimeout('Snap. Time is OUT. DAG id: yandex-rates-test')}
[2022-08-20 11:34:59,479] {logging_mixin.py:115} INFO - Sensor timed out
[2022-08-20 11:34:59,924] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
