[2022-08-20 07:37:50,810] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.insert_data scheduled__2022-08-19T15:00:00+00:00 [queued]>
[2022-08-20 07:37:52,606] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.insert_data scheduled__2022-08-19T15:00:00+00:00 [queued]>
[2022-08-20 07:37:52,651] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 07:37:52,652] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-20 07:37:52,693] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 07:37:54,364] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): insert_data> on 2022-08-19 15:00:00+00:00
[2022-08-20 07:37:55,013] {standard_task_runner.py:52} INFO - Started process 4553 to run task
[2022-08-20 07:37:55,288] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'insert_data', 'scheduled__2022-08-19T15:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmp99nejb5h', '--error-file', '/tmp/tmp6zi17anj']
[2022-08-20 07:37:55,325] {standard_task_runner.py:80} INFO - Job 29: Subtask insert_data
[2022-08-20 07:38:01,544] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.insert_data scheduled__2022-08-19T15:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-20 07:38:09,623] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-19T15:00:00+00:00
[2022-08-20 07:38:10,974] {logging_mixin.py:115} INFO - rate_date:  2022-08-20
[2022-08-20 07:38:11,025] {logging_mixin.py:115} INFO - value_:  20922.3125
[2022-08-20 07:38:11,864] {base.py:68} INFO - Using connection ID 'postgre_test_db' for task execution.
[2022-08-20 07:38:12,431] {python.py:173} INFO - Done. Returned value was: None
[2022-08-20 07:38:13,591] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=yandex-rates-test, task_id=insert_data, execution_date=20220819T150000, start_date=20220820T073750, end_date=20220820T073813
[2022-08-20 07:38:15,947] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-08-20 07:38:16,048] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 4553. PIDs of all processes in the group: [4553]
[2022-08-20 07:38:16,147] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 4553
[2022-08-20 07:38:16,410] {process_utils.py:75} INFO - Process psutil.Process(pid=4553, status='terminated', exitcode=0, started='07:37:54') (4553) terminated with exit code 0
