[2022-08-20 10:23:11,446] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [queued]>
[2022-08-20 10:23:12,427] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [queued]>
[2022-08-20 10:23:12,484] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 10:23:12,502] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-20 10:23:12,507] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 10:23:14,742] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_file> on 2022-08-19 18:00:00+00:00
[2022-08-20 10:23:15,183] {standard_task_runner.py:52} INFO - Started process 4679 to run task
[2022-08-20 10:23:15,441] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'waiting_for_file', 'scheduled__2022-08-19T18:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmp6aw_u61y', '--error-file', '/tmp/tmp58nmgcpu']
[2022-08-20 10:23:15,513] {standard_task_runner.py:80} INFO - Job 38: Subtask waiting_for_file
[2022-08-20 10:23:23,200] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-20 10:23:33,275] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=waiting_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-19T18:00:00+00:00
[2022-08-20 10:23:34,358] {base.py:68} INFO - Using connection ID 'ya_***_workshop_file_path' for task execution.
[2022-08-20 10:23:34,381] {filesystem.py:58} INFO - Poking for file C:/Users/AbduevSA-LA/Desktop/Yandex/Airflow_workshop/workshop_***-main/
[2022-08-20 10:23:35,397] {taskinstance.py:1873} INFO - Rescheduling task, marking task as UP_FOR_RESCHEDULE
[2022-08-20 10:23:36,153] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-20 10:23:37,614] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-20 11:34:55,326] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [queued]>
[2022-08-20 11:34:55,791] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [queued]>
[2022-08-20 11:34:55,795] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 11:34:55,798] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-20 11:34:55,803] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-20 11:34:56,155] {taskinstance.py:1397} INFO - Executing <Task(FileSensor): waiting_for_file> on 2022-08-19 18:00:00+00:00
[2022-08-20 11:34:56,193] {standard_task_runner.py:52} INFO - Started process 4777 to run task
[2022-08-20 11:34:56,311] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'waiting_for_file', 'scheduled__2022-08-19T18:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag.py', '--cfg-path', '/tmp/tmppr4cdn4r', '--error-file', '/tmp/tmpgabp15qa']
[2022-08-20 11:34:56,317] {standard_task_runner.py:80} INFO - Job 46: Subtask waiting_for_file
[2022-08-20 11:34:57,504] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [running]> on host 00f41d9230c6
[2022-08-20 11:34:59,066] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=waiting_for_file
AIRFLOW_CTX_EXECUTION_DATE=2022-08-19T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-19T18:00:00+00:00
[2022-08-20 11:34:59,406] {base.py:68} INFO - Using connection ID 'ya_***_workshop_file_path' for task execution.
[2022-08-20 11:34:59,523] {filesystem.py:58} INFO - Poking for file C:/Users/AbduevSA-LA/Desktop/Yandex/Airflow_workshop/workshop_***-main/
[2022-08-20 11:34:59,573] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 288, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: yandex-rates-test
[2022-08-20 11:35:00,042] {taskinstance.py:1420} INFO - Immediate failure requested. Marking task as FAILED. dag_id=yandex-rates-test, task_id=waiting_for_file, execution_date=20220819T180000, start_date=20220820T113455, end_date=20220820T113500
[2022-08-20 11:35:00,301] {standard_task_runner.py:97} ERROR - Failed to execute job 46 for task waiting_for_file (Snap. Time is OUT. DAG id: yandex-rates-test; 4777)
[2022-08-20 11:35:00,690] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-20 11:35:01,110] {logging_mixin.py:115} INFO - {'conf': <***.configuration.AirflowConfigParser object at 0x7fdb0783b690>, 'dag': <DAG: yandex-rates-test>, 'dag_run': <DagRun yandex-rates-test @ 2022-08-19 18:00:00+00:00: scheduled__2022-08-19T18:00:00+00:00, externally triggered: False>, 'data_interval_end': DateTime(2022, 8, 19, 21, 0, 0, tzinfo=Timezone('UTC')), 'data_interval_start': DateTime(2022, 8, 19, 18, 0, 0, tzinfo=Timezone('UTC')), 'ds': '2022-08-19', 'ds_nodash': '20220819', 'execution_date': DateTime(2022, 8, 19, 18, 0, 0, tzinfo=Timezone('UTC')), 'inlets': [], 'logical_date': DateTime(2022, 8, 19, 18, 0, 0, tzinfo=Timezone('UTC')), 'macros': <module '***.macros' from '/home/***/.local/lib/python3.7/site-packages/***/macros/__init__.py'>, 'next_ds': '2022-08-19', 'next_ds_nodash': '20220819', 'next_execution_date': DateTime(2022, 8, 19, 21, 0, 0, tzinfo=Timezone('UTC')), 'outlets': [], 'params': {}, 'prev_data_interval_start_success': None, 'prev_data_interval_end_success': None, 'prev_ds': '2022-08-19', 'prev_ds_nodash': '20220819', 'prev_execution_date': DateTime(2022, 8, 19, 15, 0, 0, tzinfo=Timezone('UTC')), 'prev_execution_date_success': None, 'prev_start_date_success': None, 'run_id': 'scheduled__2022-08-19T18:00:00+00:00', 'task': <Task(FileSensor): waiting_for_file>, 'task_instance': <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [failed]>, 'task_instance_key_str': 'yandex-rates-test__waiting_for_file__20220819', 'test_mode': False, 'ti': <TaskInstance: yandex-rates-test.waiting_for_file scheduled__2022-08-19T18:00:00+00:00 [failed]>, 'tomorrow_ds': '2022-08-20', 'tomorrow_ds_nodash': '20220820', 'ts': '2022-08-19T18:00:00+00:00', 'ts_nodash': '20220819T180000', 'ts_nodash_with_tz': '20220819T180000+0000', 'var': {'json': None, 'value': None}, 'conn': None, 'yesterday_ds': '2022-08-18', 'yesterday_ds_nodash': '20220818', 'exception': AirflowSensorTimeout('Snap. Time is OUT. DAG id: yandex-rates-test')}
[2022-08-20 11:35:01,112] {logging_mixin.py:115} INFO - Sensor timed out
[2022-08-20 11:35:01,294] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
