[2023-02-04 09:25:01,873] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.get_rates_rows_cnt scheduled__2023-02-04T09:20:00+00:00 [queued]>
[2023-02-04 09:25:01,885] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: yandex-rates-test.get_rates_rows_cnt scheduled__2023-02-04T09:20:00+00:00 [queued]>
[2023-02-04 09:25:01,886] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 09:25:01,886] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-02-04 09:25:01,886] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-02-04 09:25:01,911] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): get_rates_rows_cnt> on 2023-02-04 09:20:00+00:00
[2023-02-04 09:25:01,916] {standard_task_runner.py:52} INFO - Started process 11582 to run task
[2023-02-04 09:25:01,920] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'yandex-rates-test', 'get_rates_rows_cnt', 'scheduled__2023-02-04T09:20:00+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/yandex_dag_test.py', '--cfg-path', '/tmp/tmpchqm56qq', '--error-file', '/tmp/tmpxnv0_4cc']
[2023-02-04 09:25:01,921] {standard_task_runner.py:80} INFO - Job 279: Subtask get_rates_rows_cnt
[2023-02-04 09:25:02,021] {task_command.py:371} INFO - Running <TaskInstance: yandex-rates-test.get_rates_rows_cnt scheduled__2023-02-04T09:20:00+00:00 [running]> on host 39df186e1726
[2023-02-04 09:25:02,127] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yandex-rates-test
AIRFLOW_CTX_TASK_ID=get_rates_rows_cnt
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T09:20:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-04T09:20:00+00:00
[2023-02-04 09:25:02,139] {base.py:68} INFO - Using connection ID 'my_db_conn' for task execution.
[2023-02-04 09:25:02,163] {logging_mixin.py:115} INFO - 41
[2023-02-04 09:25:02,177] {python.py:173} INFO - Done. Returned value was: None
[2023-02-04 09:25:02,197] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=yandex-rates-test, task_id=get_rates_rows_cnt, execution_date=20230204T092000, start_date=20230204T092501, end_date=20230204T092502
[2023-02-04 09:25:02,252] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-04 09:25:02,286] {dagrun.py:1081} ERROR - Failed to get task '<TaskInstance: yandex-rates-test.insert_data scheduled__2023-02-04T09:20:00+00:00 [queued]>' for dag 'yandex-rates-test'. Marking it as removed.
[2023-02-04 09:25:02,311] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
